#!/bin/sh
# RYSEN-MONITOR container entrypoint
# Copyright (C) 2020-2026 Shane Daley, M0VUB <shane@freestar.network>

set -e

echo 'Starting RYSEN-Monitor...'

export AUTOBAHN_USE_NVX=0

exec python monitor.py
