<div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="card">
          <div class="card-header border-transparent">
            <h3 class="card-title" id="tbl_bridges"></h3>
          </div>
          <div class="card-body p-0">
            <div class="table-responsive p-3 mt-0">
   <!-- JSON API SYSTEM X DMR GLOBAL
	================================================== --> 
<body>     
<?php
require_once __DIR__ . '/api-config.php';

$json = dashboardFetchApiContent(API_BRIDGE_JSON_URL);
$data = $json !== false ? json_decode($json, true) : null;
$brDataArray = is_array($data) && isset($data['bridge']) && is_array($data['bridge']) ? $data['bridge'] : [];

if (count($brDataArray)) {
        echo "This table is generated by connecting to the " . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " <b>API</b>.<br />\n";
        echo "Data is live as of the time the page was loaded.<br />\n";
        echo "<br />\n";
        echo "There are <b>".count($brDataArray)."</b> official TalkGroups on the " . htmlspecialchars(API_NETWORK_LABEL, ENT_QUOTES, 'UTF-8') . " that are bridged into <b> 15 </b> modes & networks Worldwide. <br />\n";
        echo "<br />\n";
        echo "<table class=\"data-table\" cellspacing=\"0\" width=\"95%\">\n";
        echo "<tr class=\"boxtop\"><th align=\"center\">" . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . "</th><th align=\"center\">Name</th><th align=\"center\">IPSC2</th><th align=\"center\">DMRplus</th><th align=\"center\">TGIF</th><th align=\"center\">QRM</th><th align=\"center\">QuadNet</th><th align=\"center\">YSF</th><th align=\"center\">D-STAR</th><th align=\"center\">P25</th><th align=\"center\">NXDN</th><th align=\"center\">M17</th><th align=\"center\">PEANUT</th><th align=\"center\">AllStar</th><th align=\"center\">EchoLink</th></tr>\n";

        sort($brDataArray);

        foreach ( $brDataArray as $brData ) {
                $brTGID   = $brData['tgid'];
                $brName = $brData['name'];
                $brIPSC2 = $brData['ipsc2'];
                $brDMRplus = $brData['dmrplus'];
                $brTGIF = $brData['tgif'];
                $brQRM = $brData['qrm'];
                $brQNET = $brData['qnet'];
                $brYSF = $brData['ysf'];
                $brDSTAR = $brData['dstar'];
                $brP25 = $brData['p25'];
                $brNXDN = $brData['nxdn'];
                $brM17 = $brData['m17'];
                $brPEANUT = $brData['peanut'];
                $brASL = $brData['asl'];
                $brECHOLINK = $brData['echolink'];
                if (strlen($brName) > 40) {
                        $brName = substr($brName, 0, 37) . '...';
                }
                echo "  <tr class=\"boxfull\"><td align=\"center\">$brTGID</td><td align=\"left\">$brName</td><td align=\"left\">$brIPSC2</td><td align=\"left\">$brDMRplus</td><td align=\"left\">$brTGIF</td><td align=\"left\">$brQRM</td><td align=\"left\">$brQNET</td><td align=\"left\">$brYSF</td><td align=\"left\">$brDSTAR</td><td align=\"left\">$brP25</td><td align=\"left\">$brNXDN</td><td align=\"left\">$brM17</td><td align=\"left\">$brPEANUT</td><td align=\"left\">$brASL</td><td align=\"left\">$brECHOLINK</td></tr>\n";
        }

        echo "</table>\n";
}

else {
        echo "Unable to communicate with the " . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " API :(";
}
?>

<!-- Header image 
================================================== -->

<div style="width:auto; text-align: center; margin-top:5px;"><img src="img/system_x_bridge_banner_thin.jpg?random=323527528432525.24234" alt="System X Banner" class="responsive" />
</div>

<!-- FOOTER BEGIN -->
<p style="text-align: center; font-size:12px;"><span style="text-align: center;"><br>API Version 1.3 <a title="<?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> DMR Global API" target="_blank" href="<?php echo htmlspecialchars(API_BRIDGE_JSON_URL, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> API</a> M0VUB. &copy; All Rights Reserved 2021-2024<br>Contribution <a title="The Legend - Creator of Pi-Star" target="_blank" href=http://pistar.uk/>Andy Taylor MW0MWZ</a> &copy; All Rights Reserved<br>API X <a title="Rock 'n' rolla" target="_blank" href="https://github.com/shaymez">Shane Daley</a> M0VUB. &copy; All Rights Reserved<br><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> &copy; <a title="<?php echo htmlspecialchars(API_NETWORK_LABEL, ENT_QUOTES, 'UTF-8'); ?>" target="_blank" href="<?php echo htmlspecialchars(API_BRIDGE_JSON_URL, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?></a> Network<br>MMXXIV &copy;<br><br></span>
    <!-- THIS COPYRIGHT NOTICE MUST BE DISPLAYED AS A CONDITION OF THE LICENCE GRANT FOR THIS SOFTWARE. ALL DERIVATEIVES WORKS MUST CARRY THIS NOTICE -->
    <!-- This is version of System X API M0VUB 2021-2022 (v1.1)-->   						
</p>
<p style="text-align: center; font-size:16px; font-weight:bolder;"><span style="text-align: center;"><br>Display JSON below!<br><br></span>

<?php
$json_url = API_BRIDGE_JSON_URL;
$json_link = '<a href="' . htmlspecialchars($json_url, ENT_QUOTES, 'UTF-8') . '">Download JSON</a>';
echo $json_link;
?>

</p>
<!-- FOOTER END -->
</body>
            </div>
          </div>
          <div class="card-footer text-center">
            <a href="?p=home" id="lh_gohome">--Return to dashboard</a>
          </div>
        </div>
      </div>
    </div>
  </div>
