<div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="card">
          <div class="card-header border-transparent">
            <h3 class="card-title" id="tbl_tgs"></h3>
          </div>
          <div class="card-body p-0">
            <div class="table-responsive p-3 mt-0">
   <!-- JSON API SYSTEM X DMR GLOBAL
	================================================== --> 
<body>     
<?php
require_once __DIR__ . '/api-config.php';
require_once __DIR__ . '/copyright.php';

function sanitizeDashboardFlagCode($flagCode) {
        $flagCode = preg_replace('/[^0-9A-Za-z_-]/', '', (string)$flagCode);
        return $flagCode !== '' ? $flagCode : 'world';
}

function renderDashboardTalkgroupName($rawCallsign) {
        $rawCallsign = (string)$rawCallsign;
        $flagCode = 'world';

        if (preg_match('/flags\/([0-9A-Za-z_-]+)\.png/i', $rawCallsign, $matches)) {
                $flagCode = sanitizeDashboardFlagCode($matches[1]);
        }

        $flagFile = __DIR__ . '/../flags/' . $flagCode . '.png';
        if (!file_exists($flagFile)) {
                $flagCode = 'world';
        }

        $name = trim(preg_replace('/<img[^>]*>/i', '', $rawCallsign));
        if (strlen($name) > 40) {
                $name = substr($name, 0, 37) . '...';
        }

        $name = htmlspecialchars($name, ENT_QUOTES, 'UTF-8');
        $src = 'flags/' . $flagCode . '.png';
        $fallback = 'flags/world.png';

        return "<img src=\"" . $src . "\" alt=\"Country flag\" width=\"18\" height=\"13\" onerror=\"this.onerror=null;this.src='" . $fallback . "';\" /> " . $name;
}

$json = dashboardFetchApiContent(API_TG_JSON_URL);
$data = $json !== false ? json_decode($json, true) : null;
$tgDataArray = is_array($data) && isset($data['results']) && is_array($data['results']) ? $data['results'] : [];

if (count($tgDataArray)) {
        echo "This table is generated by connecting to the " . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " <b>API</b>.<br />\n";
        echo "Data is live as of the time the page was loaded.<br />\n";
        echo "<br />\n";
        echo "There are <b>".count($tgDataArray)."</b> available TalkGroups on the " . htmlspecialchars(API_NETWORK_LABEL, ENT_QUOTES, 'UTF-8') . ".<br />\n";
        echo "<br />\n";
        echo "<table class=\"data-table\" cellspacing=\"0\" width=\"95%\">\n";
        echo "<tr class=\"boxtop\"><th align=\"center\">" . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " TG Number</th><th align=\"center\">" . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " TG Name</th></tr>\n";

        sort($tgDataArray);

        foreach ( $tgDataArray as $tgData ) {
                $tgNr   = $tgData['tgid'];
                $tgName = renderDashboardTalkgroupName($tgData['callsign'] ?? '');
                echo "  <tr class=\"boxfull\"><td align=\"center\">$tgNr</td><td align=\"left\">$tgName</td></tr>\n";
        }

        echo "</table>\n";
}

else {
        echo "Unable to communicate with the " . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " API :(";
}
?>

<!-- Header image 
================================================== -->

<div style="width:auto; text-align: center; margin-top:5px;"><img src="img/system_x_banner_thin.jpg?random=323527528432525.24234" alt="System X Banner" class="responsive" />
</div>

<!-- FOOTER BEGIN -->
<p style="text-align: center; font-size:12px;"><span style="text-align: center;"><br>API Version 1.2 <a title="<?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> DMR Global Talkgroup API (JSON &amp; CSV Format)" target="_blank" href="<?php echo htmlspecialchars(API_TG_JSON_URL, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> API</a> M0VUB. &copy; All Rights Reserved 2021-<?php echo SYSTEMX_COPYRIGHT_YEAR; ?><br>Contribution <a title="The Legend - Creator of Pi-Star" target="_blank" href=http://pistar.uk/>Andy Taylor MW0MWZ</a> &copy; All Rights Reserved<br>API X <a title="RYSEN-MONITOR / System X" href="mailto:shane@freestar.network">Shane Daley</a> M0VUB &lt;shane@freestar.network&gt;. &copy; All Rights Reserved<br><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> &copy; <a title="<?php echo htmlspecialchars(API_NETWORK_LABEL, ENT_QUOTES, 'UTF-8'); ?>" target="_blank" href="<?php echo htmlspecialchars(API_TG_JSON_URL, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?></a> Network<br><?php echo SYSTEMX_COPYRIGHT_YEAR; ?> &copy;<br><br></span>
    <!-- <?php echo SYSTEMX_COPYRIGHT_LINE; ?> -->
    <!-- THIS COPYRIGHT NOTICE MUST BE DISPLAYED AS A CONDITION OF THE LICENCE GRANT FOR THIS SOFTWARE. ALL DERIVATEIVES WORKS MUST CARRY THIS NOTICE -->
    <!-- This is version of System X API M0VUB 2021-2022 (v1.1)-->   						
</p>
<p style="text-align: center; font-size:16px; font-weight:bolder;"><span style="text-align: center;"><br>Download JSON & CSV formats below!<br><br></span>

<?php
$json_url = API_TG_JSON_URL;
$csv_path = API_TG_CSV_URL;

$json_link = '<a href="' . htmlspecialchars($json_url, ENT_QUOTES, 'UTF-8') . '">Download JSON</a>';
$csv_link = '<a href="' . htmlspecialchars($csv_path, ENT_QUOTES, 'UTF-8') . '">Download CSV</a>';

echo $json_link . '<br>' . $csv_link;
?>

</p>
<!-- FOOTER END -->
</body>
            </div>
          </div>
          <div class="card-footer text-center">
            <a href="?p=home" id="lh_gohome">--Return to dashboard</a>
          </div>
        </div>
      </div>
    </div>
  </div>
