<div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="card">
          <div class="card-header border-transparent">
            <h3 class="card-title" id="tbl_tgs"></h3>
          </div>
          <div class="card-body p-0">
            <div class="table-responsive p-3 mt-0">
   <!-- JSON API SYSTEM X DMR GLOBAL
	================================================== --> 
<body>     
<?php
require_once __DIR__ . '/api-config.php';
require_once __DIR__ . '/copyright.php';

function sanitizeDashboardFlagCode($flagCode) {
        $flagCode = preg_replace('/[^0-9A-Za-z_-]/', '', (string)$flagCode);
        return $flagCode !== '' ? $flagCode : 'world';
}

function renderDashboardTalkgroupName($rawCallsign) {
        $rawCallsign = (string)$rawCallsign;
        $flagCode = 'world';

        if (preg_match('/flags\/([0-9A-Za-z_-]+)\.png/i', $rawCallsign, $matches)) {
                $flagCode = sanitizeDashboardFlagCode($matches[1]);
        }

        $flagFile = __DIR__ . '/../flags/' . $flagCode . '.png';
        if (!file_exists($flagFile)) {
                $flagCode = 'world';
        }

        $name = trim(preg_replace('/<img[^>]*>/i', '', $rawCallsign));
        if (strlen($name) > 40) {
                $name = substr($name, 0, 37) . '...';
        }

        $name = htmlspecialchars($name, ENT_QUOTES, 'UTF-8');
        $src = 'flags/' . $flagCode . '.png';
        $fallback = 'flags/world.png';

        return "<img src=\"" . $src . "\" alt=\"Country flag\" width=\"18\" height=\"13\" onerror=\"this.onerror=null;this.src='" . $fallback . "';\" /> " . $name;
}

$json = dashboardFetchApiContent(API_TG_JSON_URL);
$data = $json !== false ? json_decode($json, true) : null;
$tgDataArray = is_array($data) && isset($data['results']) && is_array($data['results']) ? $data['results'] : [];

if (count($tgDataArray)) {
        echo "This table is generated by connecting to the " . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " <b>API</b>.<br />\n";
        echo "Data is live as of the time the page was loaded.<br />\n";
        echo "<br />\n";
        $tgTotal = count($tgDataArray);
        $networkName = htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8');
        echo "There are <b>".$tgTotal."</b> available TalkGroups on the " . htmlspecialchars(API_NETWORK_LABEL, ENT_QUOTES, 'UTF-8') . ".<br />\n";
        echo "<br />\n";
        echo "<div class=\"data-table-toolbar\">\n";
        echo "  <div class=\"input-group input-group-sm\">\n";
        echo "    <div class=\"input-group-prepend\"><span class=\"input-group-text\" aria-hidden=\"true\"><i class=\"fas fa-search\"></i></span></div>\n";
        echo "    <input type=\"search\" class=\"form-control\" id=\"tbltgs_search\" placeholder=\"Search talkgroups...\" autocomplete=\"off\" spellcheck=\"false\" aria-label=\"Search talkgroups\" aria-controls=\"wwtg-table\">\n";
        echo "  </div>\n";
        echo "  <span class=\"data-table-count\" id=\"wwtg-visible-count\" aria-live=\"polite\">".$tgTotal."</span>\n";
        echo "</div>\n";
        echo "<table id=\"wwtg-table\" class=\"data-table\" cellspacing=\"0\">\n";
        echo "<thead><tr class=\"boxtop\">";
        echo "<th scope=\"col\" align=\"center\" class=\"sortable sort-asc\" data-sort-type=\"number\" tabindex=\"0\" aria-sort=\"ascending\" title=\"Click to sort\">" . $networkName . " TG Number</th>";
        echo "<th scope=\"col\" align=\"center\" class=\"sortable\" data-sort-type=\"text\" tabindex=\"0\" aria-sort=\"none\" title=\"Click to sort\">" . $networkName . " TG Name</th>";
        echo "<th scope=\"col\" align=\"center\" class=\"sortable\" data-sort-type=\"text\" tabindex=\"0\" aria-sort=\"none\" title=\"Click to sort\">Country</th>";
        echo "<th scope=\"col\" align=\"center\" class=\"sortable\" data-sort-type=\"number\" tabindex=\"0\" aria-sort=\"none\" title=\"Click to sort\">MCC</th>";
        echo "</tr></thead>\n<tbody>\n";

        sort($tgDataArray);

        foreach ( $tgDataArray as $tgData ) {
                $tgNrRaw = (string) ($tgData['tgid'] ?? '');
                $tgCountryRaw = (string) ($tgData['country'] ?? '');
                $tgMccRaw = (string) ($tgData['mcc'] ?? '');
                $rawName = trim(preg_replace('/<img[^>]*>/i', '', (string) ($tgData['callsign'] ?? '')));
                $searchHaystack = strtolower($tgNrRaw . ' ' . $rawName . ' ' . $tgCountryRaw . ' ' . $tgMccRaw);
                $tgNr   = htmlspecialchars($tgNrRaw, ENT_QUOTES, 'UTF-8');
                $tgName = renderDashboardTalkgroupName($tgData['callsign'] ?? '');
                $tgCountry = htmlspecialchars($tgCountryRaw, ENT_QUOTES, 'UTF-8');
                $tgMcc = htmlspecialchars($tgMccRaw, ENT_QUOTES, 'UTF-8');
                $sortName = htmlspecialchars($rawName, ENT_QUOTES, 'UTF-8');
                $searchAttr = htmlspecialchars($searchHaystack, ENT_QUOTES, 'UTF-8');
                echo "  <tr class=\"boxfull\" data-search=\"$searchAttr\"><td align=\"center\" data-sort=\"$tgNr\">$tgNr</td><td align=\"left\" data-sort=\"$sortName\">$tgName</td><td align=\"center\" data-sort=\"$tgCountry\">$tgCountry</td><td align=\"center\" data-sort=\"$tgMcc\">$tgMcc</td></tr>\n";
        }

        echo "</tbody>\n</table>\n";
        echo "<p class=\"data-table-empty\" id=\"tbltgs_none\" hidden>No matching talkgroups</p>\n";
        echo "<script src=\"scripts/wwtg-table.js\"></script>\n";
}

else {
        echo "Unable to communicate with the " . htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8') . " API :(";
}
?>

<!-- Header image 
================================================== -->

<div style="width:auto; text-align: center; margin-top:5px;"><img src="img/system_x_banner_thin.jpg?random=323527528432525.24234" alt="System X Banner" class="responsive" />
</div>

<!-- FOOTER BEGIN -->
<p style="text-align: center; font-size:12px;"><span style="text-align: center;"><br>API Version 1.2 <a data-bs-toggle="tooltip" title="<?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> DMR Global Talkgroup API (JSON &amp; CSV Format)" target="_blank" href="<?php echo htmlspecialchars(API_TG_JSON_URL, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> API</a> M0VUB. &copy; All Rights Reserved 2021-<?php echo SYSTEMX_COPYRIGHT_YEAR; ?><br>Contribution <a data-bs-toggle="tooltip" title="The Legend - Creator of Pi-Star" target="_blank" href=http://pistar.uk/>Andy Taylor MW0MWZ</a> &copy; All Rights Reserved<br>API X <a data-bs-toggle="tooltip" title="RYSEN-MONITOR / System X" href="mailto:shane@freestar.network">Shane Daley</a> M0VUB &lt;shane@freestar.network&gt;. &copy; All Rights Reserved<br><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?> &copy; <a data-bs-toggle="tooltip" title="<?php echo htmlspecialchars(API_NETWORK_LABEL, ENT_QUOTES, 'UTF-8'); ?>" target="_blank" href="<?php echo htmlspecialchars(API_TG_JSON_URL, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars(API_NETWORK_NAME, ENT_QUOTES, 'UTF-8'); ?></a> Network<br><?php echo SYSTEMX_COPYRIGHT_YEAR; ?> &copy;<br><br></span>
    <!-- <?php echo SYSTEMX_COPYRIGHT_LINE; ?> -->
    <!-- THIS COPYRIGHT NOTICE MUST BE DISPLAYED AS A CONDITION OF THE LICENCE GRANT FOR THIS SOFTWARE. ALL DERIVATEIVES WORKS MUST CARRY THIS NOTICE -->
    <!-- This is version of System X API M0VUB 2021-2022 (v1.1)-->   						
</p>
<p style="text-align: center; font-size:16px; font-weight:bolder;"><span style="text-align: center;"><br>Download JSON & CSV formats below!<br><br></span>

<?php
$json_url = API_TG_JSON_URL;
$csv_path = API_TG_CSV_URL;

$json_link = '<a href="' . htmlspecialchars($json_url, ENT_QUOTES, 'UTF-8') . '">Download JSON</a>';
$csv_link = '<a href="' . htmlspecialchars($csv_path, ENT_QUOTES, 'UTF-8') . '">Download CSV</a>';

echo $json_link . '<br>' . $csv_link;
?>

</p>
<!-- FOOTER END -->
</body>
            </div>
          </div>
          <div class="card-footer text-center">
            <a href="?p=home" id="lh_gohome">--Return to dashboard</a>
          </div>
        </div>
      </div>
    </div>
  </div>
